services:
  backend:
    build: ./backend
    environment:
        - ENV=debug # Use ENV from the .env file or external environment
    #   - PLE_DB_USER=${PLE_DB_USER}
    #   - PLE_DB_PASS=${PLE_DB_PASS}
    #   - PLE_DB_HOST=${PLE_DB_HOST}
    #   - PLE_DB_NAME=${PLE_DB_NAME}
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
