services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ENV=release
      - PLE_DB_USER=${PLE_DB_USER}
      - PLE_DB_PASS=${PLE_DB_PASS}
      - PLE_DB_NAME=${PLE_DB_NAME}
      - PLE_DB_HOST=${PLE_DB_HOST}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

