services:
  backend:
    build: ./backend
    environment:
        - ENV=${ENV}
        - PLE_DB_USER=${PLE_DB_USER}
        - PLE_DB_PASS=${PLE_DB_PASS}
        - PLE_DB_HOST=${PLE_DB_HOST}
        - PLE_DB_NAME=${PLE_DB_NAME}
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    environment:
        - AUTH_URL=${AUTH_URL}
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend