version: "3.8"

services:
  small_lantern:
    container_name: small_lantern_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["pnpm", "start"]
